dark.css, light.css
=> fix: Update styling of launcher results per feedback.

dark.css, light.css
Necessary for marketing videos. We'll wire it to gtk-theme later.
=> Match the launcher to shell on-hover dropdowns

src/panel_settings.ts, src/search.ts
=> Reduce launcher minimum to 640

src/window.ts
Fixes https://github.com/pop-os/beta/issues/2
=> Fix exception for Firefox

src/search.ts
This pull request adds Vim-key navigation to new launcher.
C-j acts as Down
C-k acts as Up
=> Add C-j(Down)/C-k(Up) keyevents to search launcher

src/launcher.ts
- Add /usr/local/share/applications to launcher search path
- Add snap applications to launcher search path
=> Expand app search to include snaps and /usr/local

src/app_info.ts, src/launcher.ts
- Use Gio for icon loading
- Works with other app sources
fixes #294
=> fix: Use gicon instead of icon path

TESTING.md
Tests were run against `master` and all bugs I found were filed and linked.
=> Update TESTING.md with current bugs

dark.css, light.css, schemas/org.gnome.shell.extensions.pop-shell.gschema.xml, src/active_hint.ts, src/app_info.ts, src/auto_tiler.ts, src/events.ts, src/extension.ts, src/focus.ts, src/forest.ts, src/keybindings.ts, src/launcher.ts, src/mod.d.ts, src/search.ts, src/settings.ts, src/tiling.ts, src/window.ts
=> Development Branch

src/extension.ts
=> fix: Phantom apps in dash after closing the last window in a workspace

Makefile, rebuild.sh, schemas/org.gnome.shell.extensions.pop-shell.gschema.xml, src/auto_tiler.ts, src/extension.ts, src/keybindings.ts, src/launcher.ts, src/launcherext.ts, src/panel_settings.ts, src/search.ts, src/widgets.ts
Merged PRs:
- #296 
- #343
- #347 
- #359
=> Dev PR Rollup

rebuild.sh
Need to disable the default move to monitor up and down so that moving workspace up and down actually works.
=> Fix moving window between monitors hotkey.

tsconfig.json
json file had bad formatting...
=> cleaning up bad comma in tsconfig.json

src/active_hint.ts, src/extension.ts, src/window.ts
Fixes #469, #366, #365 and #110
=> fix(active-hint): adjust focus and show desktop

src/launcher.ts
=> fix(launcher): focus on GCC when panel open

schemas/org.gnome.shell.extensions.pop-shell.gschema.xml, src/auto_tiler.ts, src/extension.ts, src/fork.ts, src/prefs.ts, src/settings.ts, src/tiling.ts
Which shall be disabled by default, but is a common request
Closes #470
=> feat: Add smart gaps feature

schemas/org.gnome.shell.extensions.pop-shell.gschema.xml, src/auto_tiler.ts, src/config.ts, src/extension.ts, src/fork.ts, src/launcher.ts, src/prefs.ts, src/search.ts, src/settings.ts, src/tiling.ts, src/window.ts, src/xprop.ts
=> feat: Add configuration file for user-defined float list

src/window.ts, src/xprop.ts
Should we move the show title toggle to the panel button now?
Closes #228 
Closes #378 
Closes #443 
Closes #32
=> fix: Show / Hide Window Title Behaviors

src/tiling.ts
=> fix: Ability to snap to bottom edge of work area

src/extension.ts, src/forest.ts
Replicated on stacking_focal locally:
- Fix on the focus staying on the stacked window that is tiled with normal windows
- Fix on the stray ghost fork
=> stacking fixes

src/launcher.ts, src/launcherext.ts, src/search.ts, src/widgets.ts
=> feat(search): Clickable search results

src/mod.d.ts, src/window.ts
=> fix: Hide active hint when window is moving

src/config.ts
Don't tile enpass assistant, it is a popup window even though it does not tell it.
=> Don't tile enpass assistant

src/extension.ts
=> fix: Watch scale-factor changes and update gaps on changes

src/window.ts
As for #544 - reapply the hint on maximized screen
=> fix: apply hint for maximized screen

src/auto_tiler.ts
And focus on one of the unstacked windows
=> fix: focus when windows are unstacked

src/launcherext.ts
=> fix: gnome-terminal -e option being deprecated

src/extension.ts
=> fix: Ignore events during screen locks

src/extension.ts, src/settings.ts
=> fix: Support static workspaces with workspace management in Pop Shell

src/mod.d.ts, src/stack.ts, src/utils.ts, src/window.ts
Use the current active hint logic to apply to the stacking button tab
=> feat: apply hint color on tabs

src/auto_tiler.ts, src/ecs.ts, src/events.ts, src/extension.ts, src/forest.ts, src/tiling.ts, src/tweener.ts, src/window.ts
=> feat: Restore window dimensions on detach

src/stack.ts
=> fix: Windows on other stacks appearing after disabling tiling

src/window.ts
=> fix: Transient windows shall no longer be forced above

src/auto_tiler.ts, src/tiling.ts
=> fix: Smart gap appearing on workspace with only stacked windows

src/extension.ts
=> fix: Ability to create upper workspace when tiling is disabled

src/extension.ts, src/tiling.ts
=> fix: Movements across monitors with management mode not always moving

src/config.ts
=> fix(exceptions): Make regular expressions case-insensitive

src/auto_tiler.ts, src/tags.ts
=> feat: Support toggling of tiling for floating exceptions

src/config.ts, src/window.ts, tsconfig.json
Hello, as a new pop!_os user I tried to configure the default position for my pointer on windows when switching with keyboard shortcuts. As it's my first pull-request for this project let me know if I miss something. Oh and can you tell me how can I test this code without breaking all my customs configuration on my own pop!_os environment ? (without breaking my custom keyboard shortcuts please)
=> Add default pointer position config when you switch in another window

README.md
Packaged for Fedora. Would be nice to mention this in README file. Thank you for such great extension!
=> docs: add Fedora installation instructions

src/window.ts
=> fix: Unmaximize of maximized window on non-active workspace causing freeze / crash

src/extension.ts
=> fix: Hide panel on lock screen

src/window.ts
=> fix: Hide active hint on fullscreen

src/extension.ts
=> fix: Close launcher dialog on screen lock

src/auto_tiler.ts, src/extension.ts, src/stack.ts
=> fix(stacking): Now supporting workspaces-on-primary-display-only behavior

src/extension.ts
Finally thought of a way to improve this. It isn't perfect, but it's significantly better than the current behavior.
Closes #673
=> fix: Improve handling of tab-dragged windows from browsers

src/extension.ts, src/window.ts
=> fix: Unminimized windows attaching incorrectly to the tree

src/focus.ts
=> fix: Disallow selecting minimized windows

src/auto_tiler.ts, src/extension.ts
=> fix: Moving tiled windows between monitors in overview

scripts/configure.sh
=> Fix (system config): disable default shortcuts

src/dialog_launcher.ts
Support for NixOS (and maybe Guix?). In which the "desktop folder" is located on each app store folder separately then added into `$XDG_DATA_DIRS` environment variables.
=> feat(launcher): Add data dirs indexer

src/dialog_launcher.ts, src/plugins/recent/main.js
- Autocomplete was not working for the files plugin
- Recent documents won't be filtered by URI anymore
=> Plugin fixes

src/extension.ts, src/fork.ts, src/mod.d.ts, src/utils.ts, src/window.ts
Working on improving the sluggishness of responses to display updates, and handling changes that should only update workareas instead of moving windows around
Closes #801
=> fix(tiling): Improve display update behavior

src/dialog_search.ts, src/mod.d.ts, src/plugins/files/main.js, src/plugins/recent/main.js
=> feat: Scrollable launcher results

src/plugins/web/main.js, src/plugins/web/meta.json
Added search functionality to Pop-shell's launcher for the following sites;
Arch Wiki 'arch'
Pop!_Planet 'pp'
Pop!_Planet Wiki 'ppw'
Reddit 'rdt'
Bandcamp 'bc'
=> Add additional sites to Plugin web.

src/plugins/web/main.js
=> fix(plugin-web): Avoid specifying language in wikipedia search

keybindings/10-pop-shell-move.xml
The grammarian in me is just bothered with the inconsistency so I corrected it. ;p
=> Correct the description for a few keybindings

src/dialog_launcher.ts
=> fix(search): Ensure that opened windows are sorted before any other launcher options

src/extension.ts
=> fix: Ensure that a dropped window is activated

src/dialog_launcher.ts, src/extension.ts, src/launcher_plugins.ts, src/launcher_service.ts, src/panel_settings.ts, src/plugin_scripts.ts, src/plugin_shell.ts, src/scripts/session-suspend.sh, src/tiling.ts
Adds the following options to the launcher:
- Toggle Active Hint
- Toggle Orientation
- Toggle Stacking
- Toggle Window Titles
- Toggle Window Tiling
Closes #827 
Closes #817
=> feat: Make Pop Shell features accessible from the launcher

icons/pop-shell-auto-off-symbolic.svg, icons/pop-shell-auto-on-symbolic.svg
=> center the icon to better align with the other panel icons

src/extension.ts, src/window.ts
Fixes two recent regressions
Closes #841
Closes #842
=> Fix pointer jumping & title bar minimizing

src/extension.ts
=> fix: Applications not getting focus after launch from overview

src/extension.ts, src/tiling.ts
=> fix: Do not unstack last window with keyboard moves

src/plugins/web/main.js, src/plugins/web/meta.json
- Move switch case to be a map instead
- Less chance of forgetting a break :safety_vest: 
- Add npm, github gist, github, and flathub
=> Mappify web plugin table

src/dialog_search.ts, src/extension.ts, src/forest.ts
=> Shell Fixes

metadata.json, src/mod.d.ts, src/prefs.ts
=> feat: Add support for GNOME 40

src/auto_tiler.ts, src/plugins/web/main.js
Add websites:
SoundCloud (sdcl)
Twitch (twitch)
Yahoo! (yh)
AliExpress (alie)
=> Add sites to websearch

dark.css, light.css, src/dialog_search.ts, src/extension.ts, src/keybindings.ts, src/mod.d.ts
- Adds hint to launcher when indeterminate
- Super key opens launcher rather than overview
Closes #925
=> COSMIC Tasks

src/dialog_launcher.ts, src/dialog_search.ts, src/extension.ts
Permits closing the launcher when pressing the overlay key
=> feat: Close launcher on super key press

src/auto_tiler.ts, src/fork.ts
=> fix: Do not alter ratio of forks on update of top level fork

README.md
There are community maintained AUR packages for the Pop Shell extension. Changes include adding three versions to "Packaging status".
=> Add community maintained AUR packages.

README.md
was added to main repository today.
=> README.md: add gentoo installation step

src/extension.ts, src/tiling.ts
=> fix(tiling) fullscreen move trigger shell api

src/window.ts
Fixes #1009
- Installed Sleek via Flatpak
- Update Settings to Minimize to Tray
=> fix: tile minimize to tray apps

src/config.ts, src/dialog_launcher.ts, src/dialog_search.ts, src/launcher_plugins.ts, src/launcher_service.ts, src/panel_settings.ts, src/plugin_help.ts, src/plugins/calc/meta.json, src/plugins/files/meta.json, src/plugins/recent/meta.json, src/plugins/terminal/meta.json, src/plugins/web/meta.json, src/utils.ts
=> Fix search activation delay / Change shortcut label in 21.04

src/auto_tiler.ts, src/config.ts, src/extension.ts
Fixes #1016  - Handle floating windows and do not tile them via toggle too
=> fix: float-exception-move

src/extension.ts
Fixes #864 
Also handles different size monitors
=> feat: handle consistent window movements

src/dialog_launcher.ts, src/extension.ts, src/mod.d.ts
Fixes #1022 workspace thumbnail, overview, launcher, switch-apps, switch-windows
Fixes #1023 - add keyboard control
=> Fix skip taskbar

schemas/org.gnome.shell.extensions.pop-shell.gschema.xml, src/extension.ts, src/plugin_shell.ts, src/prefs.ts, src/settings.ts
Fixes #1051
Fixes #1058
Fixes #1055
=> fix: regression on skip task bar

src/floating_exceptions/src/main.ts
=> fix: Constant in config.ts was renamed

src/dialog_launcher.ts, src/extension.ts
=> fix: Avoid resetting launcher on window focus

src/extension.ts
=> fix: handle proton games in gnome-shell 3.36.x

src/launcher.ts
Adds a debug and error logs to indicate what app is being launched, and if the app failed to be found.
Closes #1163
=> Fix launch of applications whose entries are in sub-directories

src/config.ts, src/mod.d.ts, src/window.ts
Closes #1104 
Closes #1170 
Closes #1149
=> Exceptions

src/launcher.ts
=> fix(launcher): Move launcher higher on low resolution displays

README.md
I noticed some broken links in the table of contents, so I have attempted to fix them
=> Fix Table of Contents

src/extension.ts
=> fix(tiling): Steam sub-menus are unclickable in tiling mode

src/auto_tiler.ts, src/forest.ts, src/tiling.ts
=> fix: Do not unstack stack on last remaining window

src/launcher.ts
=> fix(launcher): Hide previous popup menu if another is shown

src/extension.ts, src/tiling.ts
=> fix: Move to display if display is between next window and focused window

src/extension.ts
=> fix: Check if window is on same workspace when switching workspaces
