- src/extension.ts
Fixes the issue in #64. I'm not experienced with gnome-shell extension development so I'm not sure if this is the correct fix, but it did work for me :)
> Fix #64 user theme styles being overridden

- src/panel_settings.ts
- src/search.ts
The hardware key_code might not be identical to the symbol the user
intends to press (e.g in case of key remapping).
> Replace get_key_code() with get_key_symbol()

- dark.css
- light.css
- src/panel_settings.ts
Improves the layout and contents of the Panel Menu to better match the designs in #103. 
With this PR:
Fixes #103
> fix: Improve Panel Menu to match designs.

- src/extension.ts
Without this, a fullscreening a window — such as when clicking the fullscreen
button in YouTube — causes the fullscreen'd window to be tiled. This is
caused by only checking for the maximization state on a size change,
when we should check both the maximization and fullscreen state.
> fix: Fullscreening a window will now actually fullscreen it

- dark.css
- light.css
- src/events.ts
- src/extension.ts
- src/mod.d.ts
- src/search.ts
- src/settings.ts
Combines my previous PR #269 with @scaryrawr 's PR #270
The reason for this is addressed in the comments on the comments in #270
Closes #231, Closes #230
> Fixed interaction with custom shell themes

- Makefile
Just echo a `depcheck` line when checking for the typescript
compiler instead of echoing the whole sh conditional stanza.
This reduced the visual noise every time `make` is invoked
making it easier to concentrate on the actual code transformation
and packaging.
> build: Make depcheck less noisy.

- rebuild.sh
Fixes issue #92. The default dconf keybinding for toggle-message-tray is ['\<Super\>m','\<Super\>v']. This PR removes '\<Super\>m' keybinding as it conflicts with maximize window shortcut set by the pop shell.
> Fix conflicting keybinding

- schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
- src/auto_tiler.ts
- src/extension.ts
- src/keybindings.ts
- src/panel_settings.ts
moved toggle code from panel_settings and into extension (new method toggle_tiling), so it can be more generally used. Added new keybinding. I chose Super-Y because it is not used at the moment. I did not think or care much about the default assignment. 
This is the first time I've used typescript, gnome extensions and it's the most javascript I've done in years. Thanks for making it so easy to get started.
> Issue 321 (rebased) Add keyboard shortcut for toggling auto-tiling

- src/search.ts
Previously you couldn't use extension prefixes("=","d:", etc) if you accidentally put a space before them. Also solves issue with putting a space at the beginning of a normal search query.
> Spaces are now trimmed from beginning and end of search request

- src/extension.ts
- src/panel_settings.ts
This is to toggle the auto-tile switch when the keyboard shortcut is invoked. I am completely new to gnome shell extensions so if there is a better way to do this (with signals?) then please tell me.
It does however seem to work.
> Update the toggle switch in the panel based on the keyboard event.

- src/active_hint.ts
Windows with state `skip_bar` should not get the `active_hint`.
This resolves issues with launchers like ulauncher, or terminal dropdowns like guake.
> fix: do not add active_hint for windows with skip_taskbar

- src/extension.ts
Update 1: Removed the entire actor.hide() and actor.show() blocks. If not removing the actor.hide(), the dash to dock no longer shows even when moving the mouse at the edges. It seems they were meant to work in tandem.
Perhaps replace the actor.hide()/actor.show() by a different event mechanism.
***
Fixes #393
It seems like the Clutter.Actor utility is messing up the display when re-enabling tiling. It tries to show the minimized applications when it should not be. (I guess a question to the PopOS Shell devs if it is indeed required to re-tile minimized apps).
It shows an un-clickable window behind unless maximized or re-engaged minimize.
The fix seems to work well on Super + D (or hide all windows)
> fix(autotiler): do not show when minimize

- src/extension.ts
Update 1: Also checked #346
***
Fixes for #309, #411 and not sure on #237.
Tested these apps (can replicate and then are now fixed):
- Terminator
- Discord
- MS Teams Preview
- Spotify
- Slack
Electron apps or some apps that manage their own window title bars do not
send minimize events, but rather PopOS shell treats them as a grab event.
When `on_grab_end` event is  sent by these apps and the meta.minimized
attribute is set, re-using the default `extension->on_minimize()` handler should fix the empty space being left by these types of apps. Which should properly cleanup and call the `autotiler -> detach_window()` function.
> fix(autotiler): handle minimize on_grab_end

- src/window.ts
JetBrains Toolbox doesn't tile well and the window acts more like a dropdown for the taskbar.
> Add JetBrains Toolbox to blacklist

- src/window.ts
This pull request will blacklist Kotatogram Desktop's image viewer window from being tilable.
Kotatogram is a fork of Telegram Desktop, which already appears in the blacklist
> Blacklist Kotatogram's mediaviewer window from being tilable

- schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
- src/keybindings.ts
This name collided with another key binding, causing problems in gnome-control-center.This is probably a clearer name anyway.
Combined with the corresponding name change in `gnome-control-center`, this fixes https://github.com/pop-os/gnome-control-center/issues/93.
Corresponding Control Center PR: https://github.com/pop-os/gnome-control-center/pull/99.
> Rename 'search' to 'activate-launcher' in schema

- .gitignore
- src/forest.ts
Was still reproducible on #405. This additional change fixes #220.
Test case 1 (happens only on Tiling Mode):
1. Click icon Files on Dash to Dock
2. Right-click New Window from Dock.
3. Focus on one of the Files window, CTRL+Q
4. Should not leave any window dots on Dock.
Test Case 2 (happens only in Tiling Mode):
1. Toggle Title Bar on Firefox Customize page.
This is probably a question to PopShell devs on what this call is for:
```
// window.meta.change_workspace_by_index(workspace, false);
```
If this is disabled, the closing of apps via CTRL+Q does not leave any ghost dots in Dash to Dock nor toggle of Firefox's Title Bar in Customize.
> Fix closed applications dash

- src/auto_tiler.ts
- src/window.ts
There seems to be an API to adjust the window hints via GDK11. Looking for feedback @mmstick.
**Experiment**: change hints on tile, remove hints on detach. There has to be a decision on what is the smallest possible window to view, versus just splitting them all like i3?
**What works:**
- To users who want (the thrill) to resize the windows to as much as it can. Not sure who likes a 20 x 60 window.
- This makes it possible for pop-shell to control some boundaries on the size of some windows. #447 
- Edit Win Mode (`Super + Enter`), can now squeeze some windows.
**Issues:** 
- The shell responds slowly on closing windows.
- Dragging and dropping window edges using mouse is glitchy.
- During `Alt + F2, r` on windows that glitched will be closed by gnome-shell.
> feat(window): remove window hints via Gdk

- src/active_hint.ts
- src/auto_tiler.ts
- src/extension.ts
- src/forest.ts
- src/fork.ts
- src/keybindings.ts
- src/launcher.ts
- src/log.ts
- src/mod.d.ts
- src/tiling.ts
- src/tweener.ts
- src/window.ts
Pulled fixes that have been implemented along the way towards supporting stacked tiles.
- Reduces CPU cycles consumed during animations
- Toggling orientation twice will swap branches in a node
- Improves tracking and movements of the active hints
- Fixes the overlay not updating on an orientation toggle
- Fixes the notifications containing error messages from Pop Shell
- The tree is now rebalanced on detach of a window
- Fixes #449  
- Fixes #345 
- Closes #153 
- Fixes #437 
May also fix some of our outstanding active hint placement issues.
Commit c9765823bdd0e348089d39d1c50b394e29bb802f might fix the blurry windows
The stacking branch will be rebased once this is merged
> Collection of fixes from the stacking branch

- src/search.ts
For users familiar with the Rofi launcher and i3WM, selecting applications using the Emacs bindings of CTRL-N and CTRL-P is a bit of an ingrained habit. Adding the additional keybindings will also be useful any Emacs users using the Pop Shell that aren't i3 users.
> added emacs ctrl-n and ctrl-p bindings for search selection in launcher

- src/extension.ts
- src/panel_settings.ts
It seems to be working now, although I had to disable the active hint feature since it causes issues. The window title support also does not work in Wayland since we don't have an xprop equivalent.
Closes #166
> Re-enable Wayland support

- src/forest.ts
- src/stack.ts
Some small cleanup when moving stacked windows on different workspaces.
> fix: handle null entity on reparent, check parent before re-stacking siblings

- src/extension.ts
- src/stack.ts
Seeing border when a stacked window is maximized
> fix: do not show border when stack window maxed

- src/extension.ts
Do not reflow when workspace primary is enabled.
> fix: check primary monitor workspace

- dark.css
- light.css
- src/auto_tiler.ts
- src/extension.ts
- src/window.ts
Fixes #219, 
0 - gapped:
maximized:
> active-hint enhancements

- README.md
A lot of users are asking about customizing the startup `do-not-tile/floating` list. Adding this to README.md for now on how to update it.
Closes #552
> doc: add how to for floating windows

- src/extension.ts
- src/stack.ts
- src/window.ts
Make the active window stack or not as the primary actor even for the active hint. Also this will reduce the build up of St.Bin in the window group
> fix: redirect all hint logic to the active window

- src/extension.ts
When locking desktop and was tiling on, logging back in should still be tiled. Perhaps future would be to remember the stacked windows too.
> fix: re-tile when logging back in

- src/window.ts
Make sure border is not undefined. And also remove restack call to prevent loop.
> fix: remove excessive polling hint restack

- dark.css
- light.css
- rebuild.sh
- schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
- src/arena.ts
- src/auto_tiler.ts
- src/extension.ts
- src/forest.ts
- src/fork.ts
- src/keybindings.ts
- src/lib.ts
- src/mod.d.ts
- src/node.ts
- src/panel_settings.ts
- src/rectangle.ts
- src/stack.ts
- src/tiling.ts
- src/types.d.ts
- src/window.ts
Merge with https://github.com/pop-os/session/pull/22
Fixes #538 
Fixes #522 
Closes #150
Closes #488
> Add stacked tiles feature to tiling mode

- schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
- src/config.ts
- src/extension.ts
- src/forest.ts
- src/lib.ts
- src/log.ts
- src/panel_settings.ts
- src/prefs.ts
- src/settings.ts
- Added logging levels to help control the noise in journal. And let any extension developers to toggle this on their own. I had to add the current value in the panel icon, to give a first glance.
- Some of the current log imports had been renamed to just `log`.
> feat: logging levels for development (Default OFF)

- .gitignore
- rebuild.sh
This should make it easier for users of distributions with too old TypeScript
versions (e.g., Fedora 32) to try Pop Shell.
> improv(rebuild.sh): offer to install TypeScript with npm if missing or too old

- rebuild.sh
- rebuild.sh only works if you are using a supported shell (bash/zsh/sh), but not fish
- Adding shebang statement prevents fish from trying to interpret the script
> fix: rebuild.sh to work on less common shell environments

- src/extension.ts
- src/window.ts
This addresses the problem with focus-on-hover causing focus to be lost after a window is a moved to another monitor.
Closes #550
> fix: Activate window after moving across a monitor

- scripts/configure.sh
This is a quick fix to avoid the following error :
```
Extension “native-window-placement” does not exist
make: *** [Makefile:27: configure] Error 2
```
Tested in fedora 32 and 33 with gnome 3.36 and 3.38 respectively.
> Fix an error with gnome extension naming scheme

- dark.css
- light.css
- src/extension.ts
- src/window.ts
I thought it would be nice to have consistency on the accent. Including the overlay.
Would probably be overkill but here goes:
light colored borders, will use .3 opacity with the same color else
for dark colored borders, default to very light blue hint
> use the hint color for overlay

- src/extension.ts
- src/tiling.ts
- src/tweener.ts
- src/window.ts
Since the shell is now putting the windows back into their positions pre-tiling, the hint seems to look like being dragged. Need to hide the hint when it is being toggled, or when the tweener is being activated - so the experience is more snappy and smoother.
> feat: make the hint appear much smoother

- src/tweener.ts
Closes #547 
This should fix the flicker due to the higher delay of the tween observer under `on_window_tweened`.
Disabling the whole thing will be worked on a future PR.
> fix flicker tween observer as near realtime

- src/config.ts
Adds three windows/apps:
1. Solaar. Meant to be used as a dialog window. Utility to program Logitech receivers.
2. Zoom. Includes tons of dialog windows that don't tile well.
3. Slack mini panel. PIP mode when on a video call. Designed to float.
> Add dialog window and apps to the floating list

- Makefile
- README.md
- src/config.ts
Minor change to use XDG paths for the configuration file and installing for local development.
Apologies if the commit messages aren't inline with what you use, tried to base them on others, but I wasn't sure how to categorise this change.
> Use XDG paths where possible

- src/extension.ts
- src/mod.d.ts
While creating an upper workspace, the extension adds a new workspace below and push all the non-selected windows down, and in GNOME, moving a window selected as "Always on Visible Workspace" to another workspace disables that option from the window. This pull request aims to solve that issue.
Steps to reproduce the issue:
1.Open window A and window B on the first workspace you have.
2.Right-click on the window title of the window B and select "Always on Visible Workspace"
3.Select window A, and press Super+Shift+Up to create an upper workspace.
4.You will notice that window A is moved to a new workspace, but window B is not "Always on Visible Workspace" anymore.
> Don't move always on all workspaces windows

- src/window.ts
All windows should have a class, and if they don't, there's a good chance we should avoid trying to tile it.
Closes #680
> fix: Windows without a wm_class show now float by default

- src/config.ts
`system76-driver` doesn't support rescaling. I looked at trying to make it resize, but doing it with a layout that doesn't look funny seems difficult. It makes sense for that kind of program to be floating, probably.
> fix: Add floating exception for system76-driver

- src/config.ts
Adds two windows to floating exceptions:
- GNOME Termianl preferences (hamburger menu -> Preferences)
- Desktop Icons NG settings (right-click the desktop -> Settings)
Neither of these windows are resizable.
> Add GNOME Terminal preferences and DING preferences to floating exceptions

- src/stack.ts
I've occasionally run into a scenario where this codepath is hit with an `undefined` tab. This causes the stack to get stuck without an active window.
> fix: Tab disconnect sometimes tries to disconnect undefined tab

- Makefile
- debian/control
- debian/pop-shell.install
- debian/rules
- keybindings/10-pop-shell-move.xml
- keybindings/10-pop-shell-navigate.xml
- keybindings/10-pop-shell-tile.xml
See commit messages for detailed explanation and justification. This eliminates the need to patch `gnome-control-center` for `pop-shell`. Updates to the keybindings can be made without having interdependencies between pop-shell and `gnome-control-center` packages (after this one).
This should make several things easier and avoid certain problems.
Requires corresponding change to focal/groovy `gnome-control-center` package.
> Install schemas system-wide, and install Gnome Control Center keybindings xml files

- README.md
- scripts/configure.sh
Before this change, terminal seemed to be the only shortcut not being
overriden (at least on default Ubuntu 20.10) from the Keyboard Shortcuts > Launchers
section and used Ctrl+Alt+T instead of Super+T.
This change aims to make things a bit more consistent and hopefully
facilitate transition from other desktop environments (like Xfce).
Originally opened as #708 but it seems I can't edit the PR to change the base branch, hopefully that's okay.
> Override terminal launch shortcut to be in line with others

- keybindings/10-pop-shell-move.xml
- keybindings/10-pop-shell-tile.xml
These were added to focal in https://github.com/pop-os/gnome-control-center/commit/f667803fc93c41bb7dad1ace13abc018c151531d but never made it into the groovy package.
> fix(keybindings): Add missing bindings

- src/extension.ts
- src/mod.d.ts
Although we can also wait to see if the 3.38.2 release has fixed the problem.
> fix: Handle regression in 3.38.2 backports that caused nautilus to resize without moving

- src/dialog_launcher.ts
Fixes #108 
Same with things like Steam or Edge
> Improve search order based display name containing pattern

- Makefile
`gnome-extensions` is a separate package from `gnome-shell` on some systems (e.g. openSUSE), so when running operations that require it, check if it's present and show the package name if not. If someone doesn't want to install `gnome-extensions`, it's still possible to compile, install, and configure manually using those individual operations.
Closes #767.
> Check for gnome-extensions in Makefile depcheck

- src/plugins/recent/main.js
- Switched `spawnCommandLine` to `GLib.spawn_command_line_async`
> Fix: recent spawn command line async

- src/plugins/files/main.js
`xdg - open` should be `xdg-open`
> Fix: remove extra spaces in `xdg - open`

- src/plugins/files/main.js
Hide hidden directories and files unless the last component of a search query starts with "."
> fix(plugin-files): Only show hidden directories when a query starts with .

- src/dialog_add_exception.ts
- src/extension.ts
- src/mod.d.ts
- src/utils.ts
Sometimes the exceptions dialog selects a window immediately after the overview opens
> Window being selected too soon from exceptions select

- src/config.ts
The new Sideload app to install .flatpakref files (added with https://github.com/pop-os/desktop/pull/58 and https://github.com/pop-os/desktop/pull/59) does not currently resize and should be floated by default.
> Add Sideload app to default floating exceptions.

- Makefile
Fixes #760 #703 
New install of ext using source if none exists.
Existing should still work.
Wayland - need to still logout/login.
Note: `sleep 3` was added because the `gnome-extensions enable` command was being executed prior to `Meta.eval` resolves to restart the shell. If there is another elegant way, I am happy to update the PR.
> fix: update order of steps for local-install

- src/forest.ts
- src/window.ts
They cause a lot of issues with no clear solution.
Closes #780 
Fixes blurry windows
> fix: Disable window animations for tile arrangements

- src/window.ts
This is useful for stopping a pointer from continually moving back to the top left in a stacked arrangement
Closes #792
> fix(tiling): Prevent moving pointer if pointer is already in window

- schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
Keys on the numpad are considered distinct, but users seem to expect them to work the same way. (See recent discussion on  Mattermost.)
I opened an issue with Mutter suggesting these could be treated equally there: https://gitlab.gnome.org/GNOME/mutter/-/issues/1631
Alternately we could not make a change here, and instead patch Mutter. But I'm included to wait to see what upstream Gnome thinks of that. The only disadvantage I can think of to this change is a bit more clutter in Gnome Control Center when listing bindings.
> feat: Support numpad in default keybindings

- src/auto_tiler.ts
If you have three windows, and two are stacked, moving a window from the stack to attach to the adjacent window will now work instead of swapping positions.
> fix: Mouse dropping from stack to adjacent sibling

- src/plugins/web/main.js
- src/plugins/web/meta.json
The DEV Community is really useful to have in the websearch plugin.
For the keyword, I wasn't sure between `dev` or `devto`, but this can be changed anyway.
> Add DEV Community to websearch

- src/dialog_launcher.ts
- src/dialog_search.ts
This allow the use of the tab key to navigate between the launcher proposed choices, like in most launcher I know (gnome, rofi, dmenu…). This PR don't conflict with the tab completion of plugins. However, I find the behavior of the file plugin very weird since it complete to path that are not on the top of the list. In terminals and vim tab completion is triggered when it's the only choice possible. 
I would suggest rethinking tab completion, or maybe add a setting to choose the tab key behavior.
Cheers :clap:
> feat: Add support for tab navigation for the launcher

- scripts/configure.sh
I think it's better to preserve the familiar and popular <Alt>F4 shortcut. 
Thank for all your work and this extension :1st_place_medal:
> <Alt>F4 keybinding should be preserved

- src/extension.ts
This fixes #627: in tiling mode windows got raised on hover, even if the option in gnome-tweaks was disabled.
> fix: auto raise behavior in tiling mode

- src/prefs.ts
> Added margin to prefs

- src/app_info.ts
It seems this is the correct behavior, since `.desktop` files can be in subdirectories. Previously these would be shown by Gnome Shell's app grid but not in the Pop!_Shell launcher.
Fixes https://github.com/pop-os/cosmic/issues/72.
> fix: Make `load_desktop_entries()` recurse over subdirectories

- TESTING.md
- src/dialog_launcher.ts
- src/launcher_service.ts
This is working, but since the sorting algorithm doesn't take keywords into account yet, sometimes results are being sorted lower than they should be.
While working on this, I'm being conscious not to cause a regression with `cal` returning the Color control panel before Calculator or Calendar.
> Check keywords when searching apps

- src/dialog_launcher.ts
- src/launcher_service.ts
This fixes the remaining case in https://github.com/pop-os/cosmic/issues/69, searching `pavu` should return `pavucontrol` first. (It was being returned second to Document Scanner without the sorting changes.)
New sorting priority:
1. Name starts with search pattern
2. Name contains search pattern or keyword starts with or contains search pattern
3. Command starts with search pattern
4. Levenshtein comparison of search pattern with name, description, or command (whichever's closest)
5. Levenshtein comparison of search pattern with closest keyword
Opening as draft so I can also take a look at some other concerns that were brought up with searching.
> Check exec field when searching, remove hard-coded search directories

- src/extension.ts
Fixes #712
The solution is based on comments made by @sitepodmatt in https://github.com/pop-os/shell/issues/712#issuecomment-808702391 about the root cause of the issue.
This solution ignores last_focused state in handling notify::focus-window event.
> fix: Don't use last_focused state in handling notify::focus-window

- src/mod.d.ts
- src/window.ts
Fixes #990 
Fixes #1013 
Implements #882 hide hint by checking monitor count if single on max state - there seems to be a consensus to still display hint on multi-monitor setup
> fix(active-hint): bug fixes and feature max state hint

- src/dialog_launcher.ts
Changes the icon for the "Launch new window" icon from `application-default` to `new-window`.
> fix(launcher): change icon from application-default to new-window

- src/prefs.ts
Fixes the preferences window from crashing in Gnome 40.
Here are the stack details from the crash before the fix:
```
Error: No property margin on GtkGrid
Stack trace:
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
settings_dialog_view@/home/michael/.local/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:46:16
settings_dialog_new@/home/michael/.local/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:9:23
buildPrefsWidget@/home/michael/.local/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:127:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28 …
```
> fix preferences window crash in gnome 40

- src/dialog_launcher.ts
Massively speeds up launcher performance.
Fixes #1053.
> fix (launcher): avoid one-character searches

- schemas/org.gnome.shell.extensions.pop-shell.gschema.xml
- src/config.ts
- src/extension.ts
- src/plugin_shell.ts
- src/prefs.ts
- src/settings.ts
Fixes #1051 (when skip taskbar on/off)
Fixes #1055 (skip taskbar off)
Fixes #1058 (skip taskbar on/off)
Fixes #1066 - 20.04 LTS 3.36 (skip taskbar on/off)
#1023 is not on the switch.
Fixes #1034 - added Guake and ddterm to default floats
Need to test against ddterm or guake (skip taskbar but need to be floating by default - which I think need to be added to config.ts). These in addition to Sleek (minimize to tray only which is one of those types of windows that are being supported by this feature).
The skip taskbar feature is also on a switch. And by default on now in prefs.js
Hopefully this is better than the last PR.
> Fix handling skip taskbar on LTS and latest

- src/scripts/session-logout.sh
having `log` and `out` in the keywords section is great but if you type the full word logout this script does not show up. I think it should. I *think* this change will fix that.
> adding a keyword to the logout script

- src/extension.ts
Should prevent "too much recursion" errors.
> fix: Only set `default_*` globals if it not already set

- src/extension.ts
It seems in 3.38, the argument to this function was changed from the `MetaWindowActor` to the `MetaWindow`. This adds a test to correctly get the `MetaWindow` on both 3.36 and 3.38.
This should fix https://github.com/pop-os/shell/issues/1072.
> fix: Correct `_isOverviewWindow` on Gnome Shell 3.36

- src/config.ts
Fixes #1095.
(Plank has two WM_CLASS values, `plank` and `Plank`; I used the first one.)
> Add Plank to skip taskbar exceptions

- src/auto_tiler.ts
- src/extension.ts
Sometimes when a new window is opened, the window is placed in a prior-focused stack or window, rather than the actively-focused stack or window. Additionally, when a window in a stack is destroyed, sometimes the focus shifts to a completely different window or stack. These changes should fix the focus handling to correctly append to the actively-focused window, and activate a sibling in the actively-focused stack.
> fix: Focus handling improvements to fix inconsistencies in window add / remove

- src/extension.ts
> fix(tiling): support resizing/moving windows with the mouse in GNOME 40

- src/plugins/calc/main.js
Resolves https://github.com/pop-os/shell/issues/1120.
This should better match the behavior of calculators like gnome-calculator.
As far as I'm aware, the only downside of this is performance. Which probably isn't an issue when just using math.js as a calculator (vs trying to script loops of calculations).
> improv(calc): Use `BigNumber` representation

- src/extension.ts
- src/utils.ts
Since this exists, it seems better than spawning a subprocess.
This should have no impact on behavior (except theoretically being faster).
> improv: Use `imports.misc.config.PACKAGE_VERSION`

- src/extension.ts
> fix: handle gjs in 3.36

- src/auto_tiler.ts
- src/extension.ts
> fix(tiling): Windows launching onto window that isn't focused

- src/window.ts
When windows are created, they will now listen for updates to their
wm_class. This commit is motivated because some apps (notibly spotify)
don't set their wm_class property before creating the main window.
This patch allows pop-shell to work with spotify (and similar
applications) by tiling the window once it receives a valid wm_class.
This fixes #740.
> Listening for WM_CLASS change

- src/dialog_add_exception.ts
- src/extension.ts
- src/floating_exceptions/src/main.ts
Experienced GJS burning CPU the moment that I removed the local config files. Listening to `changed` events on a `Gio.File` seems to trigger the behavior.
Fixes #969
> fix: Disable config file monitoring due to GJS thread lock

- src/config.ts
Tilda is a dropdown terminal, similar to guake which is already on this list.
The 'select window' interface of popshell didn't work for this app (it doesn't appear on the window overview) so adding it by default could save some people some time.
> Add tilda to default float-rules

- README.md
openSUSE Tumbleweed has pop-shell in the main repos. This adds it to the list in the installation section in the README.
> Add openSUSE Tumbleweed package to README

- src/dbus_service.ts
- src/extension.ts
- src/launcher.ts
- src/search.ts
- src/window.ts
This will be useful in enabling a GTK launcher to know what icon to display.
Requires https://github.com/pop-os/launcher/pull/63
> fix: Give AppID of window to launcher

- src/auto_tiler.ts
- src/window.ts
This allows floating exempt windows to be toggled into tiling mode with
Super + G.  To ensure exempt windows are treated normally for movement
and placement, we must consider windows tagged with ForceTile to be
"is_tilable".
We handle these floating exempt windows separately from other windows in
toggle_floating by checking if they are exempt and then adding the
ForceTile tag to toggle floating on and then removing it when we toggle
it off.
Fixes #1222.
> fix: allow floating exempt windows to be toggled

- src/extension.ts
Patches #1069 GNOME 40 skip-taskbar version checks (#1069) to apply forwards to all versions of GNOME 40. I'm absolutely not married to this and if it is cleaner to add this on a per-version basis as a chore, let me know. 
Closes #1233
Closes #1250
> fix: Freeze in activites view on GNOME 41

- src/extension.ts
- src/mod.d.ts
Hopefully fixes #1251 for gnome 4x users. This should enable 4x to see the overview for minimized to tray apps and corresponding windows. E.g. Sleek used as a minimized to tray app
Also fixes #1094 - remove the duplicate app icons introduced by adding skip task bar windows. This also makes skip-task-bar windows behave as if they are normal icons on the switcher (if have multiple associated windows, they get the same treatment as normal - shows an arrow icon when Sleek has multiple open instances)
On Gnome 4x:
On Gnome 3x:
> fix: crash overview on 4x when min tray enabled and remove dupe app icons on switch-app

- README.md
The link on the README.md points to a non-existing channel on Pop Chat.
> Update link to the development channel on Pop_OS! Chat

- src/window.ts
Just an attempt. Perhaps fixes #1232.
Replicable when Launch new instance extension installed on Fedora with 41. Then spam opening Files from clicking on Dash
I think it is happening when the window was always maximized before. And pop-shell tries to unmax it during the tiling and the window is still _moving_.
> fix: remove transitions when opening window

- TESTING.md
https://github.com/pop-os/shell/issues/1268 has occurred at least twice and is easy to recreate, so adding a test to check for it.
> Add test for active hint on last window minimization

- src/extension.ts
GitHub issue #1264: Fix for Null "app", which prevents Alt-TAB shortcut (switch application) from working
> GitHub issue #1264: Fix for Null "app"

- src/utils.ts
Until now when installing pop-os shell into gnome-shell 3.36.9 provided
by canonical the launcher would crash with the error `log.error is not
defined` in journalctl.
The error seems to be that the import of the logging utility (`log.js`)
was never uncommented  `src/utils.js` even thought it's functionality is used. 
Doing so will solve that problem and the launcher is able to start up.
This fixes #1191
> Uncomment import of log utility in utils

- src/tiling.ts
This fixes #870, where windows could be moved to the right but not to the left monitor.
The root cause seems to be a small typo in the `locate_monitor` function, where only for the move left case the wrong pair of coordinates is compared.
The fix is therefore quite simple.
> fix: Compare correct coordinates when moving window to left monitor

- README.md
Updated README.md. The Fedora package doesn't pull in xprop which is necessary for this extension to tile properly. If xprop is not installed, pop-os-shell silently fails. Going to test and see if I can get Pop-os-shell to fail a bit more verbosely so that a normal warning will appear in the gnome extensions menu.
> docs: Added necessary dependency (xprop) for Fedora package

- src/extension.ts
This is related to #1278 and [my pull request on pop-os/launcher](https://github.com/pop-os/launcher/pull/75).
When receiving a call to `WindowQuit`, the launcher window currently stays open after the requested window is closed. The entry list in the launcher window is not updated however, with the entry for the now closed window still being present.
This change causes the launcher window to close after each `WindowQuit` call, which should be the same behavior as was implemented [before adapting the Rust launcher implementation](https://github.com/pop-os/shell/blob/e83443e96ba914f3ef990e3e410a0dbe39f11c58/src/dialog_launcher.ts#L312).
> fix: Close search window on 'WindowQuit'

- src/window.ts
> fix: Check if `display` is null on setting cursor position

- src/extension.ts
> fix(tiling): Delay focus check in case window is not focused yet

- src/config.ts
The [Junction app](https://flathub.org/apps/details/re.sonny.Junction) for choosing a web browser when clicking on links should be excluded from tiling by default.
Also: should this list be alphabetical?
> add re.sonny.Junction to DEFAULT_FLOAT_RULES

- src/forest.ts
- src/stack.ts
Useful when a web browser has a popup window and then that popup is closed
Or when testing GTK applications from an IDE
> fix: On destroy of stacked window, activate previously active tab

- src/extension.ts
- src/forest.ts
- src/window.ts
Fixes regression from last commit that causes tiling to stop working when an entity null error is triggered. It occasionally happens when two stacks are active, windows are added to both, and focus is shifted back and forth while removing and adding windows.
> fix: entity is null on window destroy from stack

- src/config.ts
Using just `title` seems more idiomatic, but I can see that other exceptions keep using `class` to refer to titles? Let me know if I should change that.
> chore: Mark Discord initial updater pop-up as floating

- src/config.ts
Pritunl desktop is a non-resizeable electron app. Adding it via Floating Window Exceptions works fine but this will save people a config step
> chore: add Pritunl client to floating exceptions

- src/search.ts
Fixes https://github.com/pop-os/shell/issues/1386.
This breaks the behavior on older Gnome Shell versions. If we want this branch to work there as well, it would be easy to make it conditional.
I don't know if there are any other undesired behavior changes here or the other places `shellReactive: true` is used, but it seems to basically work as expected now.
> [jammy] fix: On Gnome 42, close launcher on click outside of it

- scripts/configure.sh
If the extension is installed with `make local-install` to `~/./local/share/gnome-shell/extensions/`, it is now ensured that user extensions are enabled.
Improved version of pull request [#1361](https://github.com/pop-os/shell/pull/1361)
> fix: make sure to enable user extensions
